import { Link, useRoute } from "wouter";
import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import Wordmark from "@/components/Wordmark";
import { posts } from "./BlogIndex";

const easeOut = [0.23, 1, 0.32, 1] as const;

/** Full-width mosaic hero art matching the Anthropic-style colorblock aesthetic */
function MosaicHero({ palette }: { palette: string[] }) {
  // 6-column × 5-row grid of varying-span blocks
  const blocks = [
    { col: "1 / 2", row: "1 / 3", color: palette[0] },
    { col: "2 / 4", row: "1 / 2", color: palette[3] },
    { col: "4 / 6", row: "1 / 3", color: palette[1] },
    { col: "6 / 7", row: "1 / 2", color: palette[4] },
    { col: "2 / 3", row: "2 / 4", color: palette[2] },
    { col: "3 / 4", row: "2 / 3", color: palette[5] },
    { col: "3 / 5", row: "3 / 5", color: palette[0] },
    { col: "6 / 7", row: "2 / 4", color: palette[3] },
    { col: "1 / 2", row: "3 / 5", color: palette[4] },
    { col: "5 / 6", row: "3 / 4", color: palette[2] },
    { col: "5 / 7", row: "4 / 6", color: palette[1] },
    { col: "1 / 3", row: "5 / 6", color: palette[5] },
    { col: "3 / 5", row: "5 / 6", color: palette[3] },
    { col: "4 / 5", row: "3 / 4", color: palette[0] },
    { col: "2 / 3", row: "4 / 6", color: palette[2] },
  ];
  return (
    <div className="blog-post__mosaic">
      {blocks.map((b, i) => (
        <div
          key={i}
          style={{
            gridColumn: b.col,
            gridRow: b.row,
            backgroundColor: b.color,
          }}
        />
      ))}
    </div>
  );
}

const postContent: Record<string, React.ReactNode> = {
  "why-react-feels-slow": (
    <>
      <p>
        Every React developer has been there: the app works, it ships, and then someone opens a ticket
        that says "it feels sluggish." You open DevTools, record a trace, and stare at a flame graph
        that looks like it was generated by a seismograph during an earthquake.
      </p>
      <p>
        The mistake most engineers make is reaching for memoization immediately. <code>React.memo</code>,{" "}
        <code>useMemo</code>, <code>useCallback</code> — these become a reflex. But in my experience,
        the real culprits are almost always somewhere else.
      </p>
      <h2>Start with the render tree, not the component</h2>
      <p>
        Before you touch a single memo, open the React DevTools Profiler. Record five seconds of normal
        usage. Sort by "Render duration." Nine times out of ten, you'll find a handful of components
        rendering hundreds of times per second because a parent is creating a new object reference on
        every keystroke.
      </p>
      <p>
        The fix is almost never to memo the child. It's to stabilize the parent's output — move object
        and function definitions outside the render path, or reach for <code>useReducer</code> when
        your state shape is complex.
      </p>
      <h2>Context is not a state manager</h2>
      <p>
        <code>React.createContext</code> is a dependency injection mechanism. When you put rapidly-changing
        values into context — mouse position, scroll depth, form field state — every subscriber
        re-renders. This is working as designed, but it's a performance footgun.
      </p>
      <p>
        For high-frequency state, keep it local or use a proper external store. Zustand, Jotai, or even
        a simple module-level event emitter will outperform a context-based solution every time.
      </p>
      <h2>The quiet killer: list rendering without virtualization</h2>
      <p>
        A list of 500 items looks fine in development. In production on a mid-range Android device,
        it's a wall of DOM nodes. <code>react-virtual</code> or <code>@tanstack/react-virtual</code>{" "}
        takes an afternoon to integrate and the performance difference is night and day.
      </p>
      <p>
        Profile first. Measure the actual render count and duration. Then apply the smallest possible
        fix. Most of the time, the answer is embarrassingly simple — and it rarely involves adding more
        memoization.
      </p>
    </>
  ),
  "designing-systems-second-maintainer": (
    <>
      <p>
        The first time a system is built, the builder carries all the context in their head. Every
        naming decision, every abstraction boundary, every "we'll clean this up later" — all of it
        is crystal clear. The problem is that clarity lives in one person's skull, not in the code.
      </p>
      <p>
        When the second maintainer arrives — whether that's a new teammate or your future self six
        months later — the system has to speak for itself.
      </p>
      <h2>Name things for the reader, not the writer</h2>
      <p>
        The most common failure mode I see in codebases is naming that made sense in the moment it
        was written. <code>handleData</code>, <code>processItem</code>, <code>doTheThing</code> —
        these names carry zero information for someone who wasn't in the room.
      </p>
      <p>
        I use a simple rule: if I can't explain what a function does in one sentence without using
        the words "handle," "process," or "manage," the name is wrong. Names are the cheapest form
        of documentation and the most frequently read.
      </p>
      <h2>Constraints beat conventions</h2>
      <p>
        Conventions require everyone to have read the same document and to remember it under pressure.
        Constraints make the wrong thing hard to do by default. TypeScript's type system, ESLint rules,
        folder structure enforced by a linter — these are constraints that survive team turnover.
      </p>
      <h2>Leave breadcrumbs for the why, not the what</h2>
      <p>
        Code comments should explain intent, not implementation. The implementation is right there
        to read. What's not obvious is why the implementation is this way and not some other way.
        A comment that says "// we use setTimeout here because the animation library fires before
        the DOM update" is worth a thousand comments that say "// increment counter."
      </p>
    </>
  ),
  "postgres-indexes": (
    <>
      <p>
        Indexes are one of those topics where experience and intuition matter as much as
        documentation. The Postgres docs will tell you what each index type does. They won't
        tell you which ones you'll actually reach for at 11pm when a query starts timing out
        in production.
      </p>
      <p>Here's what seven years of Postgres work has taught me.</p>
      <h2>The ones I use constantly</h2>
      <p>
        <strong>B-tree on foreign keys.</strong> Postgres doesn't automatically create indexes on
        foreign keys. If you're joining on them — and you are — you need to add them yourself.
        This is the single most common index I find missing in codebases I inherit.
      </p>
      <p>
        <strong>Partial indexes.</strong> If you're frequently querying for a small subset of rows
        — active users, unprocessed jobs, recent events — a partial index with a{" "}
        <code>WHERE</code> clause will be dramatically smaller and faster than a full index.
      </p>
      <p>
        <strong>Expression indexes.</strong> When you need to query on <code>lower(email)</code> or{" "}
        <code>date_trunc('day', created_at)</code>, index the expression, not the column.
      </p>
      <h2>The ones I've abandoned</h2>
      <p>
        <strong>GiST for simple range queries.</strong> I've tried GiST indexes for date range
        queries more than once. B-tree with composite columns almost always wins in practice.
      </p>
      <p>
        The principle: measure before you index. <code>EXPLAIN ANALYZE</code> is your friend.
        Index bloat is real, and every write pays the cost of maintaining every index on the table.
      </p>
    </>
  ),
  "boring-infrastructure": (
    <>
      <p>
        There's a predictable arc to how engineering teams relate to their infrastructure.
        Early on, everything is exciting. You pick the newest database, the shiniest orchestration
        layer, the framework that just hit 1.0 last month. You move fast.
      </p>
      <p>
        Then production happens. The new database has a bug in its replication protocol.
        The orchestration layer has a breaking change that none of the plugins have caught up to.
        The framework has three competing patterns for the thing you're trying to do.
      </p>
      <h2>The cost of novelty is invisible until it isn't</h2>
      <p>
        Boring infrastructure is boring because thousands of people have already hit its edge
        cases. The weird failure modes are documented on Stack Overflow. The operational runbooks
        are written. The people you hire have used it before.
      </p>
      <p>
        Postgres over CockroachDB. Redis over a custom distributed cache. S3 over a home-built
        object store. These aren't exciting choices. They're choices that will still be working
        correctly when you're on vacation.
      </p>
      <h2>When to be boring, when not to be</h2>
      <p>
        The rule I use: be boring at the infrastructure layer, be adventurous at the product layer.
        Your users don't care what database you're running. They care whether the product solves
        their problem. Save your experimentation budget for things that directly affect them.
      </p>
    </>
  ),
  "senior-frontend-review": (
    <>
      <p>
        Most junior developers think code review is about correctness. Does the function return
        the right value? Does it handle the edge cases? Is it tested?
      </p>
      <p>
        Correctness is table stakes. By the time code reaches review, it should already work.
        What a senior reviewer is actually looking for is something different.
      </p>
      <h2>Can I understand this in six months?</h2>
      <p>
        The first question I ask when reading a PR is: if I came back to this file in six months
        with no context, could I understand what it's doing and why? If the answer is no, I ask
        for clarification — not a comment necessarily, but a naming change, a structural tweak,
        a deletion of the code that doesn't need to be there.
      </p>
      <h2>Is this adding complexity or removing it?</h2>
      <p>
        Every abstraction is a bet that the thing you're abstracting will change in the same
        ways multiple times. Sometimes that bet pays off. More often, premature abstraction just
        adds indirection without reducing duplication. I'm much more likely to ask "could we
        just inline this?" than "why isn't this abstracted?"
      </p>
      <h2>What does the next PR look like?</h2>
      <p>
        The best code I've reviewed doesn't just solve the immediate problem. It makes the next
        problem easier. A well-structured component makes the next feature a matter of adding a
        prop. A well-thought-out API design makes the next endpoint a copy-paste with minor
        variations.
      </p>
      <p>
        Review is about the future as much as the present. The best comment I ever got on a PR
        was three words: "what comes next?" It changed how I write code.
      </p>
    </>
  ),
};

export default function BlogPost() {
  const [, params] = useRoute("/writing/:slug");
  const slug = params?.slug ?? "";
  const post = posts.find((p) => p.slug === slug);

  if (!post) {
    return (
      <div className="site-shell">
        <div style={{ padding: "160px 24px", textAlign: "center" }}>
          <p>Post not found.</p>
          <Link href="/writing">← Back to Writing</Link>
        </div>
      </div>
    );
  }

  return (
    <div className="site-shell">
      <header className="site-header" data-theme="dark">
        <a className="skip-link" href="#main">Skip to content</a>
        <div className="site-header__inner">
          <Link href="/" className="brand-link" aria-label="Andrei home">
            <Wordmark />
          </Link>
          <nav className="desktop-nav" aria-label="Primary navigation">
            <Link href="/#projects">Projects</Link>
            <Link href="/writing">Writing</Link>
          </nav>
          <a href="mailto:hello@visionfx.studio" className="header-cta">Start a conversation</a>
        </div>
      </header>

      <main id="main" className="blog-post-main">
        {/* Back link */}
        <div className="content-frame">
          <motion.div
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.26, ease: easeOut }}
          >
            <Link href="/writing" className="blog-post__back">
              <ArrowLeft size={14} aria-hidden="true" />
              <span>All posts</span>
            </Link>
          </motion.div>
        </div>

        {/* Article header */}
        <div className="blog-post__header">
          <div className="blog-post__header-inner">
            <motion.p
              className="eyebrow"
              style={{ textAlign: "center", marginBottom: 28 }}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.28, ease: easeOut }}
            >
              {post.category}
            </motion.p>
            <motion.h1
              className="blog-post__title"
              initial={{ opacity: 0, y: 18 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.36, ease: easeOut, delay: 0.06 }}
            >
              {post.title}
            </motion.h1>
            <motion.p
              className="blog-post__date"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.28, ease: easeOut, delay: 0.14 }}
            >
              {post.date} · {post.readTime}
            </motion.p>
          </div>
        </div>

        {/* Mosaic hero image */}
        <motion.div
          className="blog-post__mosaic-wrap"
          initial={{ opacity: 0, scale: 0.985 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.48, ease: easeOut, delay: 0.18 }}
        >
          <MosaicHero palette={post.palette} />
        </motion.div>

        {/* Prose body */}
        <motion.article
          className="blog-post__body"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, ease: easeOut, delay: 0.28 }}
        >
          {postContent[post.slug] ?? (
            <p>Content coming soon.</p>
          )}
        </motion.article>

        {/* Footer nav */}
        <div className="blog-post__footer-nav content-frame">
          <Link href="/writing" className="blog-post__back">
            <ArrowLeft size={14} aria-hidden="true" />
            <span>Back to Writing</span>
          </Link>
        </div>
      </main>

      <footer id="footer" className="site-footer">
        <div className="content-frame">
          <div className="footer-base" style={{ borderTop: "0.5px solid #3D372B", paddingTop: 28 }}>
            <p>© {new Date().getFullYear()} Andrei. All rights reserved.</p>
            <p className="footer-meta">Built with care · Last updated <time dateTime="2026-08">August 2026</time></p>
          </div>
        </div>
        <div className="footer-wordmark" aria-hidden="true">ANDREI</div>
      </footer>
    </div>
  );
}
